version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 864981732779.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t osrm-backend:latest .
      - docker tag osrm-backend:latest   864981732779.dkr.ecr.ap-south-1.amazonaws.com/osrm-backend:latest     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 864981732779.dkr.ecr.ap-south-1.amazonaws.com/osrm-backend:latest  
